In [ ]:
# BAB 3

In [5]:
def a(): 
    print("Dzaky")

a()

Dzaky


In [34]:
def upperthree(angka):
    if angka>3: return "benar"
    else: return "salah"
upperthree(4)
upperthree(3)

'salah'

In [44]:
print ('For Loop')
for i in range(6): print(i)
    
print ('\nwhile loop')
x=7
while x>(-5):
    x-=1
    print(x)


For Loop
0
1
2
3
4
5

while loop
6
5
4
3
2
1
0
-1
-2
-3
-4
-5


In [ ]:
# BAB 4

In [45]:
import numpy as np

In [46]:
a_list=[2,3,4] #list biasa
a_list

[2, 3, 4]

In [47]:
np.array(a_list) #list array

array([2, 3, 4])

In [48]:
a_matrix=[[2,3,4],[5,6,7],[8,9,10]]
a_matrix

[[2, 3, 4], [5, 6, 7], [8, 9, 10]]

In [49]:
np.array(a_matrix) #mengubah matrix menjadi array

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [50]:
np.zeros(4) #array nilai 0

array([0., 0., 0., 0.])

In [60]:
np.zeros((4,4)) #array nilai 0 dengan 4 baris x 4 kolom

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
np.arange(25) #array bilangan cacah

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
np.arange(0,11) #array untuk bilangan antara 1 dan 11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
np.arange(0,11,3) #array untuk bilangan antara 1 dan 11 dengan kelipatan 3

array([0, 3, 6, 9])

In [61]:
np.ones(4) #array nilai 1 dengan 4 baris

array([1., 1., 1., 1.])

In [62]:
np.ones((4,4)) #array nilai 1 dengan 4 baris x 4 kolom

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
np.ones((4,4,4)) 

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [65]:
np.linspace(0,5,17) #array angka dari 0 sampai 5 berjumlah 17 angka

array([0.    , 0.3125, 0.625 , 0.9375, 1.25  , 1.5625, 1.875 , 2.1875,
       2.5   , 2.8125, 3.125 , 3.4375, 3.75  , 4.0625, 4.375 , 4.6875,
       5.    ])

In [66]:
np.eye(5) #matriks identitas dengan 5 baris dan kolom

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [68]:
np.random.rand(3) #membuat nilai random 0-1

array([0.6257128 , 0.77591401, 0.05339825])

In [69]:
np.random.rand(4,4) #membuat nilai random 4 baris dan kolom

array([[0.93717094, 0.00736553, 0.99201037, 0.37667578],
       [0.86306654, 0.08807427, 0.13590247, 0.05979773],
       [0.17116459, 0.54554416, 0.87925534, 0.79846934],
       [0.7075726 , 0.85316044, 0.01773776, 0.28409504]])

In [71]:
np.random.seed(52)
np.random.rand(3)

array([0.82311034, 0.02611798, 0.21077064])

In [73]:
np.random.seed(52) #walaupun dirandom lagi nilainya tetap sama
np.random.rand(3)

array([0.82311034, 0.02611798, 0.21077064])

In [81]:
np.random.randint(0,5,25) #random 25 angka antara 0 dan 5

array([3, 4, 2, 0, 3, 1, 2, 2, 1, 2, 0, 2, 4, 0, 1, 1, 1, 1, 2, 1, 1, 2,
       1, 3, 0])

In [ ]:
#Membuat variabel arr

In [97]:
arr=np.arange(25)
ranarr=np.random.randint(0,100,25)
arr.reshape(5,5) #reshape berguna untuk mengubah 1 dimensi menjadi 2 dimensi

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [86]:
arr.shape

(25,)

In [87]:
arr.reshape(1,25).shape

(1, 25)

In [91]:
arr.reshape(25,1).shape

(25, 1)

In [98]:
ranarr

array([36, 11, 78, 96, 63, 99, 97, 72, 30, 29, 22, 20, 85,  1, 80, 50, 16,
       18, 31, 12, 66, 35, 30,  4, 93])

In [99]:
ranarr.min() #mencari nilai minimum

1

In [100]:
ranarr.sum() #mencari jumlah total

1174

In [103]:
ranarr.argmax() #mencari indeks nilai maksimum berada

5

In [104]:
ranarr.mean() #mencari rata rata

46.96

In [105]:
arr.dtype #menentukan tipe data 

dtype('int32')

In [113]:
arr2=np.array((3.2,4.7,5.6)) #menentukan tipe data 
arr2.dtype

dtype('float64')

In [116]:
#operasi numpy
arr*arr #perkalian array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

In [117]:
arr/arr

C:\Users\alfar\AppData\Local\Temp\ipykernel_13652\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# operasi array universal

In [118]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836])

In [119]:
np.tan(arr)

array([ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
        1.15782128e+00, -3.38051501e+00, -2.91006191e-01,  8.71447983e-01,
       -6.79971146e+00, -4.52315659e-01,  6.48360827e-01, -2.25950846e+02,
       -6.35859929e-01,  4.63021133e-01,  7.24460662e+00, -8.55993401e-01,
        3.00632242e-01,  3.49391565e+00, -1.13731371e+00,  1.51589471e-01,
        2.23716094e+00, -1.52749853e+00,  8.85165604e-03,  1.58815308e+00,
       -2.13489670e+00])

In [121]:
np.log(arr)

C:\Users\alfar\AppData\Local\Temp\ipykernel_13652\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383])

In [ ]:
#penjumlahan axis

In [123]:
arrs=arr.reshape(5,5)
arrs.sum(axis=0) #array hasil penjumlahan vertikal

array([50, 55, 60, 65, 70])

In [124]:
arrs.sum(axis=1) #array hasil penjumlahan horizontal

array([ 10,  35,  60,  85, 110])

In [125]:
arrs

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [126]:
#BAB 6 PANDAS

In [127]:
import pandas as pd

In [128]:
label=['o','p','q','r','s']
vec=np.array((3,4,5,6,7))
list=[10,20,30,40,50]

In [130]:
pd.Series(data=list)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [131]:
pd.Series(data=list,index=label) #penomoran/indeks menggunakan kolom tertentu

o    10
p    20
q    30
r    40
s    50
dtype: int64

In [156]:
pd.Series(data=list,index=['Argentina','Kanada','AmerikaSerikat','Meksiko','Aljazair'])
#penomoran dengan variabel lain

Argentina         10
Kanada            20
AmerikaSerikat    30
Meksiko           40
Aljazair          50
dtype: int64

In [135]:
Utang=pd.Series(data=list,index=['Argentina','Kanada','AmerikaSerikat','Meksiko','Aljazair'])
#penomoran dengan variabel lain

In [137]:
Utang['Argentina']

10

In [161]:
np.random.seed(42)
data1=np.random.randint(100,200,(5,5))
index=['A','B','C','D','E']
column=['O','P','Q','R','S']

In [162]:
data1

array([[151, 192, 114, 171, 160],
       [120, 182, 186, 174, 174],
       [187, 199, 123, 102, 121],
       [152, 101, 187, 129, 137],
       [101, 163, 159, 120, 132]])

In [234]:
df1=pd.DataFrame(data1,index,column)
df1

O    P    Q    R    S
A  151  192  114  171  160
B  120  182  186  174  174
C  187  199  123  102  121
D  152  101  187  129  137
E  101  163  159  120  132

In [235]:
#operasi pada kolom
df1['S'] 

A    160
B    174
C    121
D    137
E    132
Name: S, dtype: int32

In [236]:
df1['new']=df1['P']+df1['R']

In [237]:
df1

O    P    Q    R    S  new
A  151  192  114  171  160  363
B  120  182  186  174  174  356
C  187  199  123  102  121  301
D  152  101  187  129  137  230
E  101  163  159  120  132  283

In [238]:
df1.drop('new',axis=1,inplace=False) #menghapus kolom
#inplace itu menentukan apakah permanent atau tidak (wajib ada)
#harus menggunakan axis untuk menghapus

O    P    Q    R    S
A  151  192  114  171  160
B  120  182  186  174  174
C  187  199  123  102  121
D  152  101  187  129  137
E  101  163  159  120  132

In [193]:
df1

O    P    Q    R    S  new
A  151  192  114  171  160  363
B  120  182  186  174  174  356
C  187  199  123  102  121  301
D  152  101  187  129  137  230
E  101  163  159  120  132  283

In [195]:
#operasi pada baris
df1.loc['D']

O      152
P      101
Q      187
R      129
S      137
new    230
Name: D, dtype: int32

In [239]:
df1.loc['old']=df1.loc['B']+df1.loc['E']

In [240]:
df1

O    P    Q    R    S  new
A    151  192  114  171  160  363
B    120  182  186  174  174  356
C    187  199  123  102  121  301
D    152  101  187  129  137  230
E    101  163  159  120  132  283
old  221  345  345  294  306  639

In [202]:
df1['Q']>150 #mengecek kebenaran nilai per kolom

A      False
B       True
C      False
D       True
E       True
old     True
Name: Q, dtype: bool

In [203]:
df1.loc['B']>150

O      False
P       True
Q       True
R       True
S       True
new     True
Name: B, dtype: bool

In [241]:
df1.reset_index() #untuk menambahkan kolom index

index    O    P    Q    R    S  new
0     A  151  192  114  171  160  363
1     B  120  182  186  174  174  356
2     C  187  199  123  102  121  301
3     D  152  101  187  129  137  230
4     E  101  163  159  120  132  283
5   old  221  345  345  294  306  639

In [242]:
#menambahkan data baru tanpa banyak koma
code='AB BC CD DE EF FG'.split() 

In [243]:
df1['code']=code

In [244]:
df1

O    P    Q    R    S  new code
A    151  192  114  171  160  363   AB
B    120  182  186  174  174  356   BC
C    187  199  123  102  121  301   CD
D    152  101  187  129  137  230   DE
E    101  163  159  120  132  283   EF
old  221  345  345  294  306  639   FG

In [246]:
df1=df1.set_index('code')

In [247]:
df1

O    P    Q    R    S  new
code                              
AB    151  192  114  171  160  363
BC    120  182  186  174  174  356
CD    187  199  123  102  121  301
DE    152  101  187  129  137  230
EF    101  163  159  120  132  283
FG    221  345  345  294  306  639

In [248]:
#datasummary
df1.describe()

O           P           Q          R           S         new
count    6.000000    6.000000    6.000000    6.00000    6.000000    6.000000
mean   155.333333  197.000000  185.666667  165.00000  171.666667  362.000000
std     43.692867   80.659779   83.860996   69.35128   68.599320  144.327406
min    101.000000  101.000000  114.000000  102.00000  121.000000  230.000000
25%    127.750000  167.750000  132.000000  122.25000  133.250000  287.500000
50%    151.500000  187.000000  172.500000  150.00000  148.500000  328.500000
75%    178.250000  197.250000  186.750000  173.25000  170.500000  361.250000
max    221.000000  345.000000  345.000000  294.00000  306.000000  639.000000

In [249]:
df1.info() #informasi data

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, AB to FG
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   O       6 non-null      int32
 1   P       6 non-null      int32
 2   Q       6 non-null      int32
 3   R       6 non-null      int32
 4   S       6 non-null      int32
 5   new     6 non-null      int32
dtypes: int32(6)
memory usage: 192.0+ bytes


In [250]:
df1.reset_index() #untuk menonaktifkan indeks pada code

code    O    P    Q    R    S  new
0   AB  151  192  114  171  160  363
1   BC  120  182  186  174  174  356
2   CD  187  199  123  102  121  301
3   DE  152  101  187  129  137  230
4   EF  101  163  159  120  132  283
5   FG  221  345  345  294  306  639

In [262]:
#missing data
mis=pd.DataFrame({'A':[1,2,np.nan,4,7],
                'B':[2,4,np.nan,np.nan,5],
                'C':[3,6,np.nan,np.nan,np.nan]})
mis

A    B    C
0  1.0  2.0  3.0
1  2.0  4.0  6.0
2  NaN  NaN  NaN
3  4.0  NaN  NaN
4  7.0  5.0  NaN

In [263]:
mis.dropna()

A    B    C
0  1.0  2.0  3.0
1  2.0  4.0  6.0

In [264]:
mis.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [265]:
mis.dropna(axis=0)

A    B    C
0  1.0  2.0  3.0
1  2.0  4.0  6.0

In [266]:
mis.dropna(thresh=2) #drop setting sesuai jumlah na nya

A    B    C
0  1.0  2.0  3.0
1  2.0  4.0  6.0
4  7.0  5.0  NaN

In [267]:
mis.fillna(value='orgil')

A      B      C
0    1.0    2.0    3.0
1    2.0    4.0    6.0
2  orgil  orgil  orgil
3    4.0  orgil  orgil
4    7.0    5.0  orgil

In [268]:
mis['B'].fillna(value='Goku')

0     2.0
1     4.0
2    Goku
3    Goku
4     5.0
Name: B, dtype: object

In [271]:
mis['B'].fillna(mis['B'].mean()) #kolom B pada data mis diisi dengan mean dari kolom B itu

0    2.000000
1    4.000000
2    3.666667
3    3.666667
4    5.000000
Name: B, dtype: float64

In [272]:
mis['A'].fillna(mis['B'].mean()) #kolom A pada data mis diisi dengan mean dari kolom B data mis

0    1.000000
1    2.000000
2    3.666667
3    4.000000
4    7.000000
Name: A, dtype: float64

In [275]:
df3=pd.read_excel('D:\Bahan Statistika\Data BBM.xlsx')

In [280]:
kelompok=df3.groupby('Klaster') #pengelompokan data berdasarkan variabel klaster

In [282]:
kelompok

In [291]:
kelompok.sum() #total masing-masing kelompok

No                                           Provinsi  Tangki (Y)  \
Klaster                                                                       
1        102  sumatera Utarakepulauan riausumatera Selatanla...    26393012   
2        126  Acehsumatera BaratjambiyogyakartaBaliKalimanta...     6568797   
3        237  bengkulubangka belitungKalimantan TengahSulawe...     3056357   

           mopen      bus     truk    sepmor       GAS      BBM  Penduduk  
Klaster                                                                    
1        5158789  1257773  2624755  22594369  21703.75  43711.4  117772.3  
2        2312555   449534  1082660  13212662   7485.27  20955.6   68034.8  
3         808664   476997   726987   4295030   2864.02   9087.3   34005.1

In [289]:
kelompok['Tangki (Y)'].mean() #rata-rata masing-masing kelompok dengan variabel Tangki(Y)

Klaster
1    2.639301e+06
2    7.298663e+05
3    2.778506e+05
Name: Tangki (Y), dtype: float64

In [292]:
kelompok.describe() #statistik deskriptif data yang telah dikelompokkan

No                                                    Tangki (Y)  \
        count       mean       std  min   25%   50%    75%   max      count   
Klaster                                                                       
1        10.0  10.200000  5.633235  2.0   6.0  10.5  12.75  21.0       10.0   
2         9.0  14.000000  9.246621  1.0   6.0  16.0  19.00  30.0        9.0   
3        11.0  21.545455  7.581077  7.0  20.0  24.0  26.50  29.0       11.0   

                       ...     BBM          Penduduk                \
                 mean  ...     75%      max    count          mean   
Klaster                ...                                           
1        2.639301e+06  ...  5283.8  17157.9     10.0  11777.230000   
2        7.298663e+05  ...  1473.9  10891.3      9.0   7559.422222   
3        2.778506e+05  ...  1112.3   2360.3     11.0   3091.372727   

                                                                  
                  std     min     25%      50%      75%      max  
Klaster                                                           
1        13092.206485   972.1  3251.9  7427.95  11667.3  39115.3  
2        10576.039418  2144.5  3375.1  4355.70   4935.3  35528.6  
3         2560.157823   870.7  1443.3  2140.00   3470.3   8490.4  

[3 rows x 72 columns]

In [293]:
kelompok['mopen'].describe() #statistik deskriptif khusus variabel mopen

count           mean            std      min       25%       50%  \
Klaster                                                                     
1         10.0  515878.900000  925573.734757   8941.0  84327.25  244316.5   
2          9.0  256950.555556  280578.870462  44812.0  64729.00  145868.0   
3         11.0   73514.909091   71095.227395    143.0  26221.50   49905.0   

              75%        max  
Klaster                       
1        429065.5  3104773.0  
2        327899.0   895810.0  
3        101021.0   232166.0

NameError: name 'df3_one' is not defined

In [306]:
#read html
table=pd.read_html('https://www.kaggle.com/datasets/rajanand/crime-in-india')

ImportError: html5lib not found, please install it

In [304]:
pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/47/6a/453160888fab7c6a432a6e25f8afe6256d0d9f2cbd25971021da6491d899/pip-23.3.1-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
    --------------------------------------- 0.0/2.1 MB 487.6 kB/s eta 0:00:05
   - -------------------------------------- 0.1/2.1 MB 544.7 kB/s eta 0:00:04
   -- ------------------------------------- 0.1/2.1 MB 847.9 kB/s eta 0:00:03
   --- ------------------------------------ 0.2/2.1 MB 908.0 kB/s eta 0:00:03
   ------ --------------------------------- 0.3/2.1 MB 1.2 MB/s eta 0:00:02
   -------- ------------------------------- 0.5/2.1 MB 1.5 MB/s eta 0:00:02
   --------- ------------------------------ 0.5/2.1 MB 1.5 

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [310]:
-m pip install html5lib

SyntaxError: invalid syntax (3443369364.py, line 1)