In [ ]:
#BAB 4 Type Data

In [1]:
#List menggunakan []
#Set menggunakan {} tidak memiliki indeks
#Tuple menggunakan ()
#Dictionary menggunakan ({})

In [3]:
lis1=[1,2,"home",True] #setiap list diawali dengan kurung siku
lis2=[]
lis3=list((1,2,3)) #jika seperti ini maka kurung biasa 2 kali

print(lis1)
print(lis2)
print(lis3)

[1, 2, 'home', True]
[]
[1, 2, 3]


In [4]:
lis4=list((1,2,"tiga"))
print(lis4)

[1, 2, 'tiga']


In [6]:
print(lis1[0])
print(lis3[2])
print(lis4[-1])

1
3
tiga


In [7]:
lis1[0]=12
print(lis1)

[12, 2, 'home', True]


In [9]:
tuple1=tuple((2,3,4,5))
tuple2=(3,4,5,"enam")

print(tuple1)
print(tuple2[-1])

(2, 3, 4, 5)
enam


In [10]:
tuple2[2]=7 #tuple tidak bisa diubah lagi

TypeError: 'tuple' object does not support item assignment

In [11]:
set1={1,2,2,3,9} #tidak bisa bernilai duplikat
print(set1)

{1, 2, 3, 9}


In [13]:
dict1=dict({1:"Apel",2:"Semangka",3:"Pepaya",4:"Jeruk"})
print(dict1)

{1: 'Apel', 2: 'Semangka', 3: 'Pepaya', 4: 'Jeruk'}


In [15]:
#keys dan values
print(dict1.keys())
print(dict1.values())

dict_keys([1, 2, 3, 4])
dict_values(['Apel', 'Semangka', 'Pepaya', 'Jeruk'])


In [16]:
dict1[1]="Anggur" #mengganti values dengan key=1
print(dict1)

{1: 'Anggur', 2: 'Semangka', 3: 'Pepaya', 4: 'Jeruk'}


In [17]:
dict1["Semangka"]=5 
print(dict1)

{1: 'Anggur', 2: 'Semangka', 3: 'Pepaya', 4: 'Jeruk', 'Semangka': 5}


In [23]:
a=12
b=15
print(a==b)
print(a/b==0.8)

False
True


In [24]:
print(a/b) #hasil desimal yang sebenarnya
print(a//b) #pembulatan ke bilangan yang lebigh rendah

0.8
0


In [30]:
p=3
q=5
#tentukan nilai dari 
p+=1 #print nya di akhir, bukan di sini
q+=1
print(p,q,q,p)

4 6 6 4


In [38]:
# IF CONDITIONAL
temperatur=27
if temperatur<=15: #if lalu kondisi 1:
    print("dingin")
elif temperatur>15 and temperatur<30: #elif lalu kondisi 2
    print("sedang")
else: print("panas") #else lalu kondisi 3



sedang


In [1]:
i=20 #i=2. Selagi i>0 cetak nilai i dengan aturan  i-2 
while i>0:
    print(i)
    i-=2

20
18
16
14
12
10
8
6
4
2


In [35]:
i=[1,2,3,4,5,6,7,8] #kesejajaran berpengaruh disini

for j in i:
    if (j==3):
        break
    print(j)

1
2


In [36]:
l=[1,2,3,4,5,6,7,8] #kesejajaran berpengaruh disini

for m in l:
    if (m==3):
        break
    print(m)
for m in l:
    if (m==5):
        continue
    print(m) #melakukan 2 perintah

1
2
1
2
3
4
6
7
8


In [37]:
l=[1,2,3,4,5,6,7,8] #kesejajaran berpengaruh disini

for m in l:
    if (m==3):
        break
for m in l:
    if (m==5):
        continue
    print(m) 

1
2
3
4
6
7
8


In [43]:
#DEF FUNGSI
def print_a():print("a")

In [44]:
print_a()

a


In [49]:
#Mencari row dan column dalam matrix
ArrayA=np.arange(16)
MatrixA=ArrayA.reshape(4,4)
MatrixA

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
row1=MatrixA[0,:]
row1

array([0, 1, 2, 3])

In [52]:
col1=MatrixA[:,0]
col1

array([ 0,  4,  8, 12])

In [57]:
#mencari elemen
elemen6=MatrixA[1,2]
elemen14=MatrixA[3,2]

print(elemen14)
print(elemen6)

14
6


In [59]:
#Operasi elemen
print(col1+row1)
print(elemen6*elemen14)

[ 0  5 10 15]
84


In [60]:
col1+row1 #kalau tanpa print gini hasilnya array([])

array([ 0,  5, 10, 15])

In [70]:
elemen6+elemen14

20

In [66]:
#perkalian Matrix
MatrixB=3*MatrixA #matrix dengan skalar
MatrixB

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33],
       [36, 39, 42, 45]])

In [67]:
MatrixA*MatrixB #matrix dengan matrix

array([[  0,   3,  12,  27],
       [ 48,  75, 108, 147],
       [192, 243, 300, 363],
       [432, 507, 588, 675]])

In [71]:
MatrixB*col1

array([[  0,  12,  48, 108],
       [  0,  60, 144, 252],
       [  0, 108, 240, 396],
       [  0, 156, 336, 540]])

In [72]:
#DATA CLEANING DAN PREPROCESSING

In [74]:
import pandas as pd

In [86]:
data1={'Nama':['Rafif','Dzaky','Zhafran','Dzaky','Budy'],
       'Nilai':[100,90,80,90,90]}
Data1=pd.DataFrame(data1)
Data1

Nama  Nilai
0    Rafif    100
1    Dzaky     90
2  Zhafran     80
3    Dzaky     90
4     Budy     90

In [87]:
#Mendeteksi duplikat 
print(Data1.duplicated())

0    False
1    False
2    False
3     True
4    False
dtype: bool


In [90]:
Data1.drop_duplicates(inplace=True) #menghapus data duplikat
print(Data1)

      Nama  Nilai
0    Rafif    100
1    Dzaky     90
2  Zhafran     80
4     Budy     90


In [91]:
data2={'Nama':['Rafif','Dzaky','Zhafran','Dzaky','Budy','Johnson','Johnson'],
       'Nilai':[100,90,80,90,90,60,50]}
Data2=pd.DataFrame(data2)
Data2

Nama  Nilai
0    Rafif    100
1    Dzaky     90
2  Zhafran     80
3    Dzaky     90
4     Budy     90
5  Johnson     60
6  Johnson     50

In [92]:
#Mendeteksi duplikat 
print(Data2['Nama'].duplicated())

0    False
1    False
2    False
3     True
4    False
5    False
6     True
Name: Nama, dtype: bool


In [95]:
Data2['Nama'].drop_duplicates(inplace=True) #menghapus data duplikat tidak bisa
print(Data2) 

      Nama  Nilai
0    Rafif    100
1    Dzaky     90
2  Zhafran     80
3    Dzaky     90
4     Budy     90
5  Johnson     60
6  Johnson     50


In [98]:
data3={'Nilai':[90,89,82,87,84,91]}
Data3=pd.DataFrame(data3)
Data3

Nilai
0     90
1     89
2     82
3     87
4     84
5     91

In [100]:
Data3_N=(Data3-Data3.min())/(Data3.max()-Data3.min()) #Normalisasi data
Data3_N

Nilai
0  0.888889
1  0.777778
2  0.000000
3  0.555556
4  0.222222
5  1.000000

In [101]:
data4={'Nilai':[90,89,82,87,84,121]}
Data4=pd.DataFrame(data4)
Data4

Nilai
0     90
1     89
2     82
3     87
4     84
5    121

In [105]:
Z=np.abs((Data4-Data4.mean())/Data4.std()) #Mendeteksi data outliers
out=Data4[Z>1].dropna()
print("Outliers:")
print(out)

#Data Tanpa Outliers
Data4_B=Data4[Z<=1].dropna()
print("Data tanpa iutliers:")
print(Data4_B)

Outliers:
   Nilai
5  121.0
Data tanpa iutliers:
   Nilai
0   90.0
1   89.0
2   82.0
3   87.0
4   84.0


In [107]:
data5={'Nama':('Rafif','Dzaky','Zhafran','Robi','Cyntya'),
      'Kelas':(12,11,10,12,11),
      'Nilai_PKN':(90,81,86,89,83),
      'Nilai_IPA':(98,87,86,82,85)}
Data5=pd.DataFrame(data5)
Data5

Nama  Kelas  Nilai_PKN  Nilai_IPA
0    Rafif     12         90         98
1    Dzaky     11         81         87
2  Zhafran     10         86         86
3     Robi     12         89         82
4   Cyntya     11         83         85

In [109]:
print("Nilai PKN Terbaik") #Filtering data berdasarkan kriteria tertentu
filt1=Data5[Data5['Nilai_PKN']>85]
print(filt1)
print("")
print("Nilai IPA Terbaik")
filt2=Data5[Data5['Nilai_IPA']>85]
print(filt2)

Nilai PKN Terbaik
      Nama  Kelas  Nilai_PKN  Nilai_IPA
0    Rafif     12         90         98
2  Zhafran     10         86         86
3     Robi     12         89         82

Nilai IPA Terbaik
      Nama  Kelas  Nilai_PKN  Nilai_IPA
0    Rafif     12         90         98
1    Dzaky     11         81         87
2  Zhafran     10         86         86


In [110]:
sort1=Data5.sort_values('Nilai_PKN') #Sort data berdasarkan kriteria tertentu
print(sort1)
print("")
sort2=Data5.sort_values('Nilai_IPA')
print(sort2)

      Nama  Kelas  Nilai_PKN  Nilai_IPA
1    Dzaky     11         81         87
4   Cyntya     11         83         85
2  Zhafran     10         86         86
3     Robi     12         89         82
0    Rafif     12         90         98

      Nama  Kelas  Nilai_PKN  Nilai_IPA
3     Robi     12         89         82
4   Cyntya     11         83         85
2  Zhafran     10         86         86
1    Dzaky     11         81         87
0    Rafif     12         90         98


In [111]:
#Penanganan pada data yang hilang/missing value
data6={'Nama':('Fathiyah','Lathifah','Lucy','Lyla','Rafif'),
      'Kelas':(12,11,10,12,11),
      'Nilai_PKN':(90,81,86,89,None),
      'Nilai_IPA':(98,None,86,82,85)}
Data6=pd.DataFrame(data6)
Data6

Nama  Kelas  Nilai_PKN  Nilai_IPA
0  Fathiyah     12       90.0       98.0
1  Lathifah     11       81.0        NaN
2      Lucy     10       86.0       86.0
3      Lyla     12       89.0       82.0
4     Rafif     11        NaN       85.0

In [115]:
mean_PKN=Data6['Nilai_PKN'].mean()
mean_IPA=Data6['Nilai_IPA'].mean()
Data6_1=Data6['Nilai_PKN'].fillna(mean_PKN)
print("Data yang sudah diisi nilai PKN yang kosong")
print(Data6_1)

Data yang sudah diisi nilai PKN yang kosong
0    90.0
1    81.0
2    86.0
3    89.0
4    86.5
Name: Nilai_PKN, dtype: float64


In [117]:
Data6_2=Data6['Nilai_IPA'].fillna(mean_IPA)
print("Data yang sudah diisi nilai IPA yang kosong")
print(Data6_2)

Data yang sudah diisi nilai IPA yang kosong
0    98.00
1    87.75
2    86.00
3    82.00
4    85.00
Name: Nilai_IPA, dtype: float64


In [119]:
print(Data5.loc[2]) #Mencari lokasi berdasarkan indeks data

Nama         Zhafran
Kelas             10
Nilai_PKN         86
Nilai_IPA         86
Name: 2, dtype: object


In [121]:
#Conditional Indexing
filt_con1=Data5[Data5['Nilai_PKN']<85]
filt_con2=Data5[Data5['Nilai_IPA']<85]
print(filt_con1)
print(filt_con2)

     Nama  Kelas  Nilai_PKN  Nilai_IPA
1   Dzaky     11         81         87
4  Cyntya     11         83         85
   Nama  Kelas  Nilai_PKN  Nilai_IPA
3  Robi     12         89         82
